### PR TITLE
template: add template for modules team

### PR DESCRIPTION
**Pull request by MylesBorins**

### CODE REVIEW

**Comment by mhdawson** [comment]
You need an observers file as well even if it is empty.

**Comment by MylesBorins** [comment]
updated

**Comment by MylesBorins** [comment]
Was this put in production? we didn't get a meeting generated

**Comment by mhdawson** [comment]
I'll have to check when I'm at home with access to the machine that generates them.  There is a difference in the capitalization between the template and the name in the calendar so it could also have been that.

**Pull request merged**
