### PR TITLE
Create meeting_base_package_metadata_interoperability_collab_space.md

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
Adds meeting template file for Package Metadata Interoperability collab space

### CODE REVIEW

**Comment by mhdawson** [comment]
@Ethan-Arrowood there are 4 files that need to be added.  Look for the 4 files that end with cross_project_council as examples

**Comment by mhdawson** [comment]
These is also this doc with more info on the templates -https://github.com/nodejs/create-node-meeting-artifacts/blob/main/TEMPLATES_DOCUMENTATION.md

**Comment by Ethan-Arrowood** [comment]
Okay I think I got it this time. Please take a look @mhdawson , thank you!

**Comment by mhdawson** [comment]
Ok tested it out and make a couple of fixes and should no generate for the next meeting.

**Pull request merged**
