### PR TITLE
invite regular members to meetings

### PR DESCRIPTION
**Pull request by Trott**
With the recent change to the TSC charter, there is a "regular member" category of non-voting TSC member. There is consensus to invite these members to meetings. These members have no obligation to attend meetings but are welcome to and, if this change lands, will be notified of meetings.

@nodejs/tsc

### CODE REVIEW

**Review by RaisinTen — APPROVED** [review]

**Review by legendecas — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]

**Comment by RafaelGSS** [comment]
Maybe we should ping them here in advance?

**Comment by Trott** [comment]
> Maybe we should ping them here in advance?

Sure!

@addaleax
@bnoordhuis
@ChALkeR
@codebytere
@danbev
@fhinkel
@gabrielschulhof
@mscdex
@MylesBorins
@rvagg
@TimothyGu

**Comment by bnoordhuis** [comment]
Thanks for the ping. I won't be able to attend.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
