### PR TITLE
fix: Markdownlint issues in templates

### PR DESCRIPTION
**Pull request by nschonni**
- Bare URLs
- Trailing whitespace
- List spacing

### CODE REVIEW

**Comment by nschonni** [comment]
@Trott related to https://github.com/nodejs/TSC/pull/991, but I didn't try to wrap any of the `$GITHUB_ISSUE$` values for now

**Review by Trott — APPROVED** [review]

**Comment by nschonni** [comment]
@mhdawson looks like you got the latest TSC meetings in one go 😉 
Not sure if you hit any small minor adjustments that this hits

**Review by Trott — APPROVED** [review]
Rubber-stamp LGTM

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
