### PR TITLE
add templates for tooling group

### PR DESCRIPTION
**Pull request by boneskull**
@mhdawson 	I've added the templates, but don't have a Zoom link.  What should I put there?

### CODE REVIEW

**Comment by boneskull** [comment]
@mhdawson 	Updated with Zoom link.

**Comment by mhdawson** [comment]
Going to land and see if it looks ok.

**Comment by mhdawson** [comment]
Looks like issue was generated ok.  I ran it manually this time so when there is a regular time let me know and I'll add it to the right cron job.

**Comment by mhdawson** [comment]
Reference to issue that was created https://github.com/nodejs/tooling/issues/9

**Pull request merged**
