### PR TITLE
chore(templates): sunset the website redesign initative

### PR DESCRIPTION
**Pull request by ovflowd**
This PR removes the Website Redesign Initiative templates as the Initiative is being sunset.

### CODE REVIEW

**Comment by ovflowd** [comment]
cc @nodejs/tsc @richardlau

**Review by joesepi — APPROVED** [review]
I deleted the calendar entry as well

**Review by tniessen — APPROVED** [review]

**Review by danielleadams — APPROVED** [review]

**Review by RaisinTen — APPROVED** [review]

**Comment by mhdawson** [comment]
Ok deleted entry from my automation that does generation as well.

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
