### PR TITLE
add templates for performance team

### PR DESCRIPTION
**Pull request by anonrig**
I'm not quite for about CALENDAR_ID and zoom link for the meetings.

### CODE REVIEW

**Comment by mhdawson** [comment]
@anonrig there need to be one for observers_performance as well. Even if it is empty.

**Comment by mhdawson** [comment]
The CALENDAR_ID should just be the same as for the other meetings. Once we get you access to zoom we can set up a specific meeting link for the performance team.

**Comment by anonrig** [comment]
I force pushed with the observers_performance file. Only missing thing in this pull request is this line: `Link for participants: https://zoom.us/j/REPLACEME`

**Comment by mhdawson** [comment]
@anonrig you should now be able to access zoom and create a new webinar for the performance team. You can set it as recurring with no fixed time and use it for every meeting.

**Comment by anonrig** [comment]
@mhdawson I updated the Zoom link. Thanks for sharing!

**Comment by mhdawson** [comment]
@anonrig when is the meeting/is it in the calendar? If not if you give me the recurring time I'll add it to the calendar and then land/test this interms of generation.

**Comment by anonrig** [comment]
November 14 - 1 PM - EDT was the first meeting. We'll do recurring 2-week meetings. I believe @joesepi already added it to the Node calendar.

**Comment by mhdawson** [comment]
Tested, should be good to go now.

**Pull request merged**
