### PR TITLE
update TSC invitation list

### PR DESCRIPTION
**Pull request by Trott**
@nodejs/tsc

### CODE REVIEW

**Comment by mhdawson** [comment]
@Trott Ruben was added as an observer in https://github.com/nodejs/create-node-meeting-artifacts/pull/83 and showed up in the recent meeting.  

If you think he needs to be part of the invited list instead of observer, then you should add the removal of him from the observer list to this PR.

**Comment by Trott** [comment]
> @Trott Ruben was added as an observer in #83 and showed up in the recent meeting invite.
> 
> If you think he needs to be part of the invited list instead of observer, then you should add the removal of him from the observer list to this PR.

Ah, didn't realize there were two lists....

**Comment by Trott** [comment]
> Ah, didn't realize there were two lists....

All fixed up.

**Comment by mhdawson** [comment]
Landing since this is a reflection of reality and already has 3 approvals

**Comment by jasnell** [comment]
@gireeshpunathil should be added as an observer also given that @mcollina has nominated him back to coincide with @BridgeAR's nomination: https://github.com/nodejs/TSC/issues/817#issuecomment-585851434

**Pull request merged**
