### PR TITLE
remove mylesborins from tsc_invited

### PR DESCRIPTION
**Pull request by Trott**

### CODE REVIEW

**Comment by Trott** [comment]
@mhdawson Don't know if you check GitHub notifications on weekends, but if so, I imagine you'll want to merge this before the automated meeting creation job happens this weekend.

**Comment by Trott** [comment]
@nodejs/tsc @MylesBorins A few approvals would probably be a good thing.

**Review by aduh95 — APPROVED** [review]
That seems like the kind of things that would benefit from being outputed by a script that reads nodejs/node README (rather than a separate file that must be kept in sync).

**Review by richardlau — APPROVED** [review]

**Review by gireeshpunathil — APPROVED** [review]

**Comment by Trott** [comment]
> That seems like the kind of things that would benefit from being outputed by a script that reads nodejs/node README (rather than a separate file that must be kept in sync).

Another possibility is to use the GitHub API to retrieve the members of the `@nodejs/collaborators` team, but yeah, regardless of the method chosen, automation would certainly be preferable.

**Review by RaisinTen — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
